// Code generated by SQLBoiler 4.0.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DownloadQueue        string
	DownloadedAnimations string
}{
	DownloadQueue:        "downloadQueue",
	DownloadedAnimations: "downloadedAnimations",
}
